-- Create Tables
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DataSync_ExportConfigurations')
BEGIN
    CREATE TABLE DataSync_ExportConfigurations (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        AppId NVARCHAR(50) NOT NULL,
        AppName NVARCHAR(100) NOT NULL,
        DbServerIP NVARCHAR(50) NOT NULL,
        DbName NVARCHAR(50) NOT NULL,
        TableName NVARCHAR(50) NOT NULL,
        DateColumn NVARCHAR(50) NOT NULL,
        CustomQuery NVARCHAR(MAX) NULL,
        Enabled BIT NOT NULL
    );
END

-- Ensure column exists if table already exists (Migration support)
IF EXISTS (SELECT * FROM sys.tables WHERE name = 'DataSync_ExportConfigurations')
BEGIN
    IF NOT EXISTS (SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('DataSync_ExportConfigurations') AND name = 'CustomQuery')
    BEGIN
        ALTER TABLE DataSync_ExportConfigurations ADD CustomQuery NVARCHAR(MAX) NULL;
    END
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DataSync_ExportLogs')
BEGIN
    CREATE TABLE DataSync_ExportLogs (
        Id BIGINT IDENTITY(1,1) PRIMARY KEY,
        AppId NVARCHAR(50) NOT NULL,
        TableName NVARCHAR(50) NOT NULL,
        RequestTimestamp DATETIME DEFAULT GETDATE(),
        FromDate DATETIME NOT NULL,
        ToDate DATETIME NOT NULL,
        Status NVARCHAR(50) NOT NULL,
        RecordsCount INT DEFAULT 0,
        ErrorMessage NVARCHAR(MAX) NULL
    );
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DataSync_ApiClients')
BEGIN
    CREATE TABLE DataSync_ApiClients (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        ClientId NVARCHAR(50) NOT NULL UNIQUE,
        ClientSecretHash NVARCHAR(255) NOT NULL,
        ClientName NVARCHAR(100) NOT NULL,
        IsActive BIT DEFAULT 1,
        Created DATETIME DEFAULT GETDATE()
    );
END

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'DataSync_RefreshTokens')
BEGIN
    CREATE TABLE DataSync_RefreshTokens (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        AppId NVARCHAR(50) NOT NULL,
        Token NVARCHAR(255) NOT NULL,
        Expires DATETIME NOT NULL,
        Created DATETIME NOT NULL,
        Revoked DATETIME NULL
    );
END

-- Seed Data
IF NOT EXISTS (SELECT * FROM DataSync_ExportConfigurations)
BEGIN
    INSERT INTO DataSync_ExportConfigurations (AppId, AppName, DbServerIP, DbName, TableName, DateColumn, Enabled)
    VALUES 
    ('app-001', 'Sales App', '192.168.1.10', 'SalesDb', 'Orders', 'OrderDate', 1),
    ('app-002', 'Inventory App', '192.168.1.11', 'InventoryDb', 'Stock', 'LastUpdated', 1),
    ('app-003', 'HR App', '192.168.1.12', 'HRDb', 'Employees', 'JoinDate', 1);
END

IF NOT EXISTS (SELECT * FROM DataSync_ApiClients)
BEGIN
    -- Secret: secret123 (Hash needs to be generated by the app, inserting placeholder for now or a known hash if available)
    -- For this seed, we will assume the app handles client creation or we insert a known test client.
    -- Using a placeholder hash for 'secret123' (In real scenario, use the helper to generate this)
    INSERT INTO DataSync_ApiClients (ClientId, ClientSecretHash, ClientName, IsActive)
    VALUES ('test-client', 'J/L7Z0+V9+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X=', 'Test Client', 1);
END
